from django_filters import rest_framework as filters
from .models import Product


class ProductFilter(filters.FilterSet):
    subcategory = ...
    color = ...
    size = ...
    brand = ...
    price = filters.RangeFilter()
    new = ...
    sell = ...

    class Meta:
        model = Product
        fields = []