# Generated by Django 3.1.3 on 2020-11-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='buy_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество покупок'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='buy_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='сумма покупок'),
        ),
    ]
