# Generated by Django 3.1.3 on 2020-11-19 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название бренда')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('brand_image', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='логотип бренда')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='слаг')),
                ('title', models.CharField(help_text='верхняя одежда/обувь/нижнее белье', max_length=30, verbose_name='категория')),
                ('category_image', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='картинка категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='текст отзыва')),
                ('adding_date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='слаг')),
                ('title', models.CharField(help_text='мужчинам/женщинам', max_length=30, verbose_name='для кого')),
                ('section_image', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='слаг')),
                ('title', models.CharField(help_text='кофты/футболки/носки', max_length=30, verbose_name='подкатегория')),
                ('subcategory_image', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='картинка подкатегории')),
                ('category', models.ForeignKey(help_text='категория', on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('sizes', models.CharField(choices=[('Одежда', (('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'))), ('Обувь', (('33,5', '33,5'), ('34,5', '34,5'), ('35', '35'), ('35,5', '35,5'), ('36', '36'), ('36,5', '36,5'), ('37', '37'), ('37,5', '37,5'), ('38', '38'), ('38,5', '38,5'), ('39', '39'), ('39,5', '39,5'), ('40', '40'), ('40,5', '40,5'), ('41', '41'), ('41,5', '41,5'), ('42', '42'), ('42,5', '42,5'), ('43', '43'), ('43,5', '43,5'), ('44', '44'), ('44,5', '44,5'), ('45', '45'), ('45,5', '45,5'), ('46', '46'), ('46,5', '46,5'), ('47', '47'), ('47,5', '47,5'), ('48', '48'), ('48,5', '48,5'), ('49', '49'), ('49,5', '49,5'), ('50', '50')))], max_length=50, verbose_name='размеры')),
                ('title', models.CharField(help_text='макс. длина 75 символов', max_length=75, verbose_name='название товара')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='стоимость')),
                ('new_product', models.BooleanField(blank=True, default=False, verbose_name='новинка')),
                ('discount', models.IntegerField(blank=True, default=False, verbose_name='скидка в гривнах')),
                ('adding_date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('header_image', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='главная картинка')),
                ('image_1', models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='картинка 1')),
                ('image_2', models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='картинка 2')),
                ('image_3', models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='картинка 3')),
                ('image_4', models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='картинка 4')),
                ('image_5', models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='картинка 5')),
                ('image_6', models.ImageField(blank=True, upload_to='images/%Y-%m-%d/', verbose_name='картинка 6')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='бренд')),
                ('feedbacks', models.ManyToManyField(blank=True, to='shop.FeedBack', verbose_name='отзывы')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory', verbose_name='подкатегория')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(help_text='раздел', on_delete=django.db.models.deletion.CASCADE, to='shop.section', verbose_name='раздел'),
        ),
    ]
