# Generated by Django 3.1.3 on 2020-11-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201119_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='опубликован'),
        ),
    ]
