# Generated by Django 3.1.3 on 2020-11-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201122_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'размер',
                'verbose_name_plural': 'размеры',
                'ordering': ['size'],
            },
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['pk'], 'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['pk'], 'verbose_name': 'подкатегория', 'verbose_name_plural': 'подкатегории'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(null=True, to='shop.Sizes', verbose_name='размеры'),
        ),
    ]
