# Generated by Django 3.1.3 on 2020-12-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201202_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='header',
            field=models.CharField(max_length=100, null=True, verbose_name='заголовок'),
        ),
    ]
