# Generated by Django 3.1.3 on 2020-12-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_feedback_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='опубликован'),
        ),
    ]
