# Generated by Django 3.1.3 on 2020-12-03 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0014_auto_20201203_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('logo', models.ImageField(upload_to='images/%Y-%m-%d/', verbose_name='логотип')),
            ],
            options={
                'verbose_name': 'служба доставки',
                'verbose_name_plural': 'службы доставки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=30, verbose_name='имя')),
                ('patronym', models.CharField(max_length=30, verbose_name='отчество')),
                ('phone', models.CharField(max_length=30, verbose_name='телефон')),
                ('email', models.CharField(max_length=50, verbose_name='e-mail')),
                ('region', models.CharField(max_length=50, verbose_name='область')),
                ('district', models.CharField(max_length=50, verbose_name='район')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('adding_date', models.DateTimeField(auto_now_add=True, verbose_name='дата оформления')),
                ('is_done', models.BooleanField(default=False, verbose_name='выполнен')),
                ('consumer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.delivery', verbose_name='доставка')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30, verbose_name='размер')),
                ('color', models.CharField(max_length=30, verbose_name='цвет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
