# Generated by Django 3.1.3 on 2020-12-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_delivery_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-adding_date'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='опубликовано'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='опубликовано'),
        ),
    ]
