# Generated by Django 3.1.3 on 2020-12-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201206_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='patronym',
        ),
    ]
