# Generated by Django 3.1.3 on 2021-01-22 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0019_auto_20201206_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'единица заказа', 'verbose_name_plural': 'единицы заказа'},
        ),
        migrations.AlterField(
            model_name='order',
            name='consumer',
            field=models.ForeignKey(blank=True, default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
    ]
